package Visual;

import MODELO.*;
import DAO.*;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author KAICON
 */
public class FormCompra extends javax.swing.JDialog {

    private DAOCompra dao = new DAOCompra();
    private DAOFornecedor daoF = new DAOFornecedor();
    private DAOFuncionario daoFu = new DAOFuncionario();
    private DAOItensCompra daoI = new DAOItensCompra();

    public void atualizaValorTotal(int linha) {
        Compra obj = listCompra.get(linha);
        double valorTotal = 0;

        for (ItensCompra itensCompra : daoI.getLista()) {
            if (itensCompra.getCompra().equals(obj)) {
                valorTotal += itensCompra.getQntd() * itensCompra.getProduto().getPrecoVenda();
            }
        }
        txtValorTotal.setText(Double.toString(valorTotal));
    }

    public void atualizaTabela() {
        listCompra.clear();
        listCompra.addAll(dao.getLista());
        int linha = listCompra.size() - 1;
        if (linha >= 0) {
            tableCompra.setRowSelectionInterval(linha, linha);
            tableCompra.scrollRectToVisible(tableCompra.getCellRect(linha, linha, true));
            atualizaValorTotal(linha);
        }
    }

    public void trataEdicao(boolean editando) {

        btnCancelar.setEnabled(editando);
        btnSalvar.setEnabled(editando);
        btnEditar.setEnabled(!editando);
        btnExcluir.setEnabled(!editando);
        btnNovo.setEnabled(!editando);
        tabGuias.setEnabled(!editando);

        btnFechar.setEnabled(!editando);
        btnAnterior.setEnabled(!editando);
        btnPrimeiro.setEnabled(!editando);
        btnUltimo.setEnabled(!editando);
        btnProximo.setEnabled(!editando);

        txtData.setEnabled(editando);
        cbFuncionario.setEnabled(editando);
        cbFornecedor.setEnabled(editando);

        tableCompra.setEnabled(!editando);

    }

    public boolean validaCampos() {
        if (!(txtData.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a Data de Compra");
            txtData.requestFocus();
            return false;
        }
        if (!(cbFuncionario.getSelectedIndex() >= 0)) {
            JOptionPane.showMessageDialog(null, "Informe o Funcionario responsável pela compra");
            cbFuncionario.requestFocus();
            return false;

        }
        if (!(cbFornecedor.getSelectedIndex() >= 0)) {
            JOptionPane.showMessageDialog(null, "Informe o Fornecedor de Compras da compra");
            cbFornecedor.requestFocus();
            return false;
        }
        return true;
    }

    public FormCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setMinimumSize(new java.awt.Dimension(1366, 695));
        initComponents();
        listFornecedor.clear();
        listFornecedor.addAll(daoF.getLista());
        listFuncionario.clear();
        listFuncionario.addAll(daoFu.getLista());
        btnItensCompra.setEnabled(false);
        atualizaTabela();
        trataEdicao(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listFuncionario = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Funcionario>())
        ;
        listFornecedor = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Fornecedor>())
        ;
        listCompra = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Compra>())
        ;
        converter_Datas = new Visual.Converter_Datas();
        panelNavegacao = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        panelOrganizacao = new javax.swing.JPanel();
        tabGuias = new javax.swing.JTabbedPane();
        panelListagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompra = new javax.swing.JTable();
        panelDados = new javax.swing.JPanel();
        panelAcoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtIdCompra = new javax.swing.JTextField();
        javax.swing.text.MaskFormatter maskData = null;
        try{
            maskData = new javax.swing.text.MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
        }catch(Exception x){ }
        txtData = new javax.swing.JFormattedTextField(maskData);
        txtValorTotal = new javax.swing.JTextField();
        lblIdCompra = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox<>();
        cbFornecedor = new javax.swing.JComboBox<>();
        btnItensCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realização de Compras");

        panelNavegacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));
        panelNavegacao.setLayout(new java.awt.GridLayout(1, 0));

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        panelNavegacao.add(btnAnterior);

        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        panelNavegacao.add(btnPrimeiro);

        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        panelNavegacao.add(btnUltimo);

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        panelNavegacao.add(btnProximo);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        panelNavegacao.add(btnFechar);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listCompra, tableCompra);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id_Compra}"));
        columnBinding.setColumnName("Id_ Compra");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorTotal}"));
        columnBinding.setColumnName("Valor Total");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fornecedor}"));
        columnBinding.setColumnName("Fornecedor");
        columnBinding.setColumnClass(MODELO.Fornecedor.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${funcionario}"));
        columnBinding.setColumnName("Funcionário");
        columnBinding.setColumnClass(MODELO.Funcionario.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataFormatada}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tableCompra);

        javax.swing.GroupLayout panelListagemLayout = new javax.swing.GroupLayout(panelListagem);
        panelListagem.setLayout(panelListagemLayout);
        panelListagemLayout.setHorizontalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelListagemLayout.setVerticalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabGuias.addTab("Listagem", panelListagem);

        panelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        panelAcoes.setLayout(new java.awt.GridLayout(1, 0));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panelAcoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelAcoes.add(btnEditar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panelAcoes.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelAcoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panelAcoes.add(btnExcluir);

        txtIdCompra.setEditable(false);
        txtIdCompra.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCompra, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id_Compra}"), txtIdCompra, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtData.setToolTipText("dd/mm/yyyy");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCompra, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.data}"), txtData, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(converter_Datas);
        bindingGroup.addBinding(binding);

        txtValorTotal.setEditable(false);
        txtValorTotal.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCompra, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.valorTotal}"), txtValorTotal, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblIdCompra.setText("Id_Compra");

        lblData.setText("Data");

        lblValorTotal.setText("Valor Total");

        lblFuncionario.setText("Funcionário");

        lblFornecedor.setText("Fornecedor");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listFuncionario, cbFuncionario);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCompra, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.funcionario}"), cbFuncionario, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listFornecedor, cbFornecedor);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCompra, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fornecedor}"), cbFornecedor, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        btnItensCompra.setText("Itens de Compra");
        btnItensCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItensCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTotal)
                                    .addComponent(lblData)
                                    .addComponent(lblIdCompra)
                                    .addComponent(lblFuncionario)
                                    .addComponent(lblFornecedor))
                                .addGap(47, 47, 47)
                                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtData)
                                    .addComponent(cbFuncionario, 0, 160, Short.MAX_VALUE)
                                    .addComponent(cbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorTotal)))
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(btnItensCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 241, Short.MAX_VALUE))
                    .addComponent(panelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCompra)
                    .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedor)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnItensCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabGuias.addTab("Dados", panelDados);

        javax.swing.GroupLayout panelOrganizacaoLayout = new javax.swing.GroupLayout(panelOrganizacao);
        panelOrganizacao.setLayout(panelOrganizacaoLayout);
        panelOrganizacaoLayout.setHorizontalGroup(
            panelOrganizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrganizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGuias)
                .addContainerGap())
        );
        panelOrganizacaoLayout.setVerticalGroup(
            panelOrganizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrganizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGuias)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOrganizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOrganizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnItensCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItensCompraActionPerformed
        int linhaSelecionada = tableCompra.getSelectedRow();
        Compra obj = listCompra.get(linhaSelecionada);
        FormItensCompra formC = new FormItensCompra(null, true, obj);
        formC.setLocationRelativeTo(null);
        formC.setVisible(true);
        formC.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnItensCompraActionPerformed
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        int linha = tableCompra.getSelectedRow();
        if ((linha - 1) >= 0) {
            linha--;
        }
        tableCompra.setRowSelectionInterval(linha, linha);
        tableCompra.scrollRectToVisible(tableCompra.getCellRect(linha, 0, true));
        atualizaValorTotal(linha);
    }//GEN-LAST:event_btnAnteriorActionPerformed
    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        tableCompra.setRowSelectionInterval(0, 0);
        tableCompra.scrollRectToVisible(tableCompra.getCellRect(0, 0, true));
        atualizaValorTotal(0);
    }//GEN-LAST:event_btnPrimeiroActionPerformed
    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        int linha = tableCompra.getRowCount() - 1;
        tableCompra.setRowSelectionInterval(linha, linha);
        tableCompra.scrollRectToVisible(tableCompra.getCellRect(linha, 0, true));
        atualizaValorTotal(linha);
    }//GEN-LAST:event_btnUltimoActionPerformed
    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        int linha = tableCompra.getSelectedRow();
        if ((linha + 1) <= tableCompra.getRowCount() - 1) {
            linha++;
        }
        tableCompra.setRowSelectionInterval(linha, linha);
        tableCompra.scrollRectToVisible(tableCompra.getCellRect(linha, 0, true));
        atualizaValorTotal(linha);
    }//GEN-LAST:event_btnProximoActionPerformed
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        listCompra.add(new Compra());
        int linha = listCompra.size() - 1;
        tableCompra.setRowSelectionInterval(linha, linha);
        txtData.requestFocus();
        trataEdicao(true);
    }//GEN-LAST:event_btnNovoActionPerformed
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtData.requestFocus();
        trataEdicao(true);
    }//GEN-LAST:event_btnEditarActionPerformed
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean edit = true;
        if (validaCampos()) {
            int linhaSelecionada = tableCompra.getSelectedRow();
            Compra obj = listCompra.get(linhaSelecionada);
            dao.salvar(obj);
            atualizaTabela();
            trataEdicao(false);
            btnItensCompra.setEnabled(edit);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.atualizaTabela();
        trataEdicao(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Confirme a exclusão");
        if (option == 0) {
            try {
                int linhaSelecionada = tableCompra.getSelectedRow();
                Compra obj = listCompra.get(linhaSelecionada);
                dao.delete(obj);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não há Compra para excluisão");
            }
            atualizaTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnItensCompra;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cbFornecedor;
    private javax.swing.JComboBox<String> cbFuncionario;
    private Visual.Converter_Datas converter_Datas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblIdCompra;
    private javax.swing.JLabel lblValorTotal;
    private java.util.List<Compra> listCompra;
    private java.util.List<Fornecedor> listFornecedor;
    private java.util.List<Funcionario> listFuncionario;
    private javax.swing.JPanel panelAcoes;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelListagem;
    private javax.swing.JPanel panelNavegacao;
    private javax.swing.JPanel panelOrganizacao;
    private javax.swing.JTabbedPane tabGuias;
    private javax.swing.JTable tableCompra;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtIdCompra;
    private javax.swing.JTextField txtValorTotal;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
