package Visual;

/**
 *
 * @author KAICON
 */
public class FormAjuda extends javax.swing.JDialog {

    /**
     * Creates new form Ajuda
     */
    public FormAjuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setMinimumSize(new java.awt.Dimension(1366, 695));
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSobre = new javax.swing.JPanel();
        panelPrincipalSobre = new javax.swing.JPanel();
        txtTítulo = new javax.swing.JTextField();
        panelOrganizacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSobre = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");

        panelSobre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sobre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtTítulo.setEditable(false);
        txtTítulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtTítulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTítulo.setText("Distribuidora VLFH");

        txtSobre.setEditable(false);
        txtSobre.setBackground(new java.awt.Color(240, 240, 240));
        txtSobre.setColumns(20);
        txtSobre.setRows(5);
        txtSobre.setText("\n **Está parte, estará imcompleta até que haja vinculação com o Banco, contendo \nintruções de para uso dos Formulários de cadastro, de Compras e Vendas.");
        txtSobre.setBorder(null);
        jScrollPane1.setViewportView(txtSobre);

        javax.swing.GroupLayout panelOrganizacaoLayout = new javax.swing.GroupLayout(panelOrganizacao);
        panelOrganizacao.setLayout(panelOrganizacaoLayout);
        panelOrganizacaoLayout.setHorizontalGroup(
            panelOrganizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelOrganizacaoLayout.setVerticalGroup(
            panelOrganizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrganizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPrincipalSobreLayout = new javax.swing.GroupLayout(panelPrincipalSobre);
        panelPrincipalSobre.setLayout(panelPrincipalSobreLayout);
        panelPrincipalSobreLayout.setHorizontalGroup(
            panelPrincipalSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOrganizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTítulo, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalSobreLayout.setVerticalGroup(
            panelPrincipalSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOrganizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSobreLayout = new javax.swing.GroupLayout(panelSobre);
        panelSobre.setLayout(panelSobreLayout);
        panelSobreLayout.setHorizontalGroup(
            panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipalSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSobreLayout.setVerticalGroup(
            panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipalSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelOrganizacao;
    private javax.swing.JPanel panelPrincipalSobre;
    private javax.swing.JPanel panelSobre;
    private javax.swing.JTextArea txtSobre;
    private javax.swing.JTextField txtTítulo;
    // End of variables declaration//GEN-END:variables
}
